# Generated by Django 3.1.7 on 2023-10-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_manager', '0001_initial'),
        ('post_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.node'),
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.node'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_manager.post'),
        ),
    ]
